name: CI/CD Pipeline 1

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Run Pipeline 1
        run: echo "Running on Runner 1"
